name: HealAndFeed
version: 3.5.0
main: Kylan1940\HealAndFeed\Main
api: 5.0.0
author: Kylan1940
softdepend: 
- BedrockEconomy

commands:
  heal:
    description: "Add max player health"
    permission: "healandfeed.heal.self"
  heal <player>:
    description: "Add max other player health"
    permission: "healandfeed.heal.other"
  healall:
    description: "Add max player health to all online player(s)"
    permission: "healandfeed.heal.all"
  feed:
    description: "Restore hunger player and hunger saturation player"
    permission: "healandfeed.feed.self"
  feed <player>:
    description: "Restore hunger other player and hunger saturation other player"
    permission: "healandfeed.feed.other"
  feedall:
    description: "Restore hunger player and hunger saturation all online player(s)"
    permission: "healandfeed.feed.all"
  healfeed:
    description: "HealAndFeedUI"
    permission: "healandfeed.ui"
    
permissions:
  healandfeed.heal.self:
    description: "Permission for heal command"
    default: op
  healandfeed.heal.other:
    description: "Permission for heal other player command"
    default: op
  healandfeed.heal.all:
    description: "Permission for heal all command"
    default: op
  healandfeed.feed.self:
    description: "Permission for feed command"
    default: op
  healandfeed.feed.other:
    description: "Permission for feed other player command"
    default: op
  healandfeed.feed.all:
    description: "Permission for feed all command"
    default: op
  healandfeed.ui:
    description: "Permission for HealAndFeed UI command"
    default: op