name: HealAndFeed
version: 1.0.0
main: Kylan1940\HealAndFeed\Main
api: 3.0.0
author: Kylan1940
commands:
  heal:
    description: "Added max player health"
    usage: /heal
    permission: "healandfeed-heal.command"
  feed:
    description: "Restore hunger player and hunger saturation player"
    usage: /feed
    permission: "healandfeed-feed.command"
  healfeed:
    description: "Heal and Feed UI Command"
    usage: /healfeed
    permission: "healandfeed-ui.command"