name: HealAndFeed
version: 3.0.0
main: Kylan1940\HealAndFeed\Main
api: 5.0.0
author: Kylan1940

commands:
  heal:
    description: "Add max player health"
    permission: "healandfeed-heal.command"
  feed:
    description: "Restore hunger player and hunger saturation player"
    permission: "healandfeed-feed.command"
    
permissions:
  healandfeed-heal.command:
    description: "Permission for heal command"
    default: op
  healandfeed-feed.command:
    description: "Permission for feed command"
    default: op